### ISSUE TITLE
Does BinICA still provide a benefit over RunICA? Windows x64 Binary?

### ISSUE THREAD

**Issue by andrewxstewart** [sccn/binica#1]
Hi Arno,

Does BinICA still provide a benefit over RunICA?

If so, might it be worth including a compiled binary for Windows x64 for easier install for our Windows users?

Thanks,
Andrew X Stewart, ERPLAB

**Comment by arnodelorme** [comment]
Hi Andrew,

The main benefit of BinICA is that it does not require Matlab. If you have a binary windows 64 version, by all mean issue a pull request and I will accept it.

Best wishes,

Arno
