### ISSUE TITLE
Makefile for Windows?

### ISSUE THREAD

**Issue by Wolverine1122** [sccn/binica#2]
I have installed clapack and blas libraries on Windows 10. I am confused about the next steps. Am I supposed to construct a makefile? There seems to be makefiles only for UNIX systems.

**Comment by arnodelorme** [comment]
You should get the binary for windows. It is precompiled.

**Comment by Wolverine1122** [comment]
Thanks for help. I looked at the wiki of the repo and how to handle the pre-compiled binary. One of the steps is to link an executable ICA. I can't find the one suitable for Windows.

There are files such `ica_linux`, `ica_sun`, `ica_sgi`.

I was expecting to see `ica_windows` or a similar file with `.exe` extension.

**Comment by arnodelorme** [comment]
You may find the compiled binary here https://github.com/sccn/binica/wiki

**Comment by Wolverine1122** [comment]
Thanks. I have already downloaded the binary file. The problem is there is no Windows executable file inside it. There are executables for UNIX but not for Windows. Attached is the content of the binary file.

![image](https://user-images.githubusercontent.com/74157130/196516068-9e4058b2-7ff2-4c19-bd19-e40e2351001c.png)

**Comment by arnodelorme** [comment]
There was an older version as well. I have edited the page to make it more prominent. Can you try it?

**Comment by Wolverine1122** [comment]
Sorry took me a while to test it out. It is working! Thanks a lot for your help.

**Comment by Wolverine1122** [comment]
Oh, one thing I noticed is that one of the commands on the wiki to test the binica is:
`EEG = pop_runica(EEG,'icatype','binica', 'extended',1,'interupt','on');`

It looks like it isn't quite right. Something is not lining up with the dataset. I kept getting poprunica error when it gets tmpdata, just like the issue here but with binica:
https://www.mathworks.com/matlabcentral/answers/456959-can-t-run-ica-eeglab

BinICA is working with real dataset and with `rand(x,y)`

**Comment by arnodelorme** [comment]
I have a MAC, not Windows, so I cannot really test, but if you find the problem, let us know.
